version: '3'
services:
  app:
    build: .
    ports:
      - "5000:80"
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - PGPASSWORD=reallydumbpassword
    depends_on:
      - postgres
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_PASSWORD=reallydumbpassword
